name: test coverage coverall

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '.github/workflows/test-coverage-coveralls.yml'
      - 'environment.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.py'
      - '.github/workflows/test-coverage-coveralls.yml'
      - 'environment.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: nicklucche
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: nicklucche/avalanche-rl:latest
  unit-test:
    if: github.repository == 'ContinualAI/avalanche-rl'
    name: unit test
    runs-on: ubuntu-latest
    container:
      image: nicklucche/avalanche-rl:latest
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.6", "3.7", "3.8", "3.9"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - run: | 
          whoami
          echo $(pwd)
          which python
          python -c 'import sys; print(sys.version_info[:])'
          which pip
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
      - run: |
          source /app/venv/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
          python -c 'import avalanche_rl; print(avalanche_rl.__version__)'
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # - name: download atari roms
      #   run: |
      #     wget http://www.atarimania.com/roms/Roms.rar
      #     unar Roms.rar
      #     python -m atari_py.import_roms Rars/
      - name: install coverage.py and coverralls
        # export PATH="/home/avalanche-user/.local/bin:$PATH"
        run: |
          whoami
          echo $(pwd)
          source /app/venv/bin/activate
          pip install coverage
          pip install coveralls
          pip install pytest
          pip install pytest-cov
      - name: python unit test
        id: unittest
        run: |
          source /app/venv/bin/activate
          coverage run -m pytest
  #     - name: Upload coverage data to coveralls.io
  #       run: |
  #         coveralls --service=github
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
  #         COVERALLS_PARALLEL: true

  # coveralls:
  #   if: github.repository == 'ContinualAI/avalanche-rl'
  #   name: Indicate completion to coveralls.io
  #   needs: unit-test
  #   runs-on: ubuntu-latest
  #   container: python:3-slim
  #   steps:
  #     - name: Finished
  #       run: |
  #         pip3 install --upgrade coveralls
  #         coveralls --finish
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
